#!/bin/sh
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/blocked.jpg" -o static/img/copied/blocked.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/cursive.jpg" -o static/img/copied/cursive.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/hinted.png" -o static/img/copied/hinted.png --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/unhinted.png" -o static/img/copied/unhinted.png --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/lamy.jpg" -o static/img/copied/lamy.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/dash_screenshot.png" -o static/img/copied/dash_screenshot.png --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/arial_and_helvetica.jpg" -o static/img/copied/arial_and_helvetica.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/arial_and_helvetica.jpg" -o static/img/copied/arial_and_helvetica.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/taglines.png" -o static/img/copied/taglines.png --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/bird.jpg" -o static/img/copied/bird.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/guitars_stripes.jpg" -o static/img/copied/guitars_stripes.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/clock.jpg" -o static/img/copied/clock.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/treap.png" -o static/img/copied/treap.png --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/treap.png" -o static/img/copied/treap.png --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/skiplist.png" -o static/img/copied/skiplist.png --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/skiplist.png" -o static/img/copied/skiplist.png --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/appending-instead-of-prepending/linked_list_file_1.jpg" -o static/img/copied/posts/appending-instead-of-prepending/linked_list_file_1.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/appending-instead-of-prepending/linked_list_file_2.jpg" -o static/img/copied/posts/appending-instead-of-prepending/linked_list_file_2.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/appending-instead-of-prepending/linked_list_file_3.jpg" -o static/img/copied/posts/appending-instead-of-prepending/linked_list_file_3.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/facebook_deactivated.png" -o static/img/copied/facebook_deactivated.png --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/laplace-fourier-transforms/1.jpg" -o static/img/copied/posts/laplace-fourier-transforms/1.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/laplace-fourier-transforms/2.jpg" -o static/img/copied/posts/laplace-fourier-transforms/2.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/laplace-fourier-transforms/3.jpg" -o static/img/copied/posts/laplace-fourier-transforms/3.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/laplace-fourier-transforms/4.jpg" -o static/img/copied/posts/laplace-fourier-transforms/4.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/laplace-fourier-transforms/5.jpg" -o static/img/copied/posts/laplace-fourier-transforms/5.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/snmp-part-ii/get-request-response.jpg" -o static/img/copied/posts/snmp-part-ii/get-request-response.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/snmp-part-ii/get-request-response-pdus.jpg" -o static/img/copied/posts/snmp-part-ii/get-request-response-pdus.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/snmp-part-ii/wireshark-screenshot.png" -o static/img/copied/posts/snmp-part-ii/wireshark-screenshot.png --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/snmp-part-ii/discovery.jpg" -o static/img/copied/posts/snmp-part-ii/discovery.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/snmp-part-ii/communication-diagram.jpg" -o static/img/copied/posts/snmp-part-ii/communication-diagram.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/snmp-part-i/observium-vlans.png" -o static/img/copied/posts/snmp-part-i/observium-vlans.png --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/snmp-part-i/fws-624.jpg" -o static/img/copied/posts/snmp-part-i/fws-624.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/beaglebone/beaglebone.jpg" -o static/img/copied/posts/beaglebone/beaglebone.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/the-crazy-one/excerpt.png" -o static/img/copied/posts/the-crazy-one/excerpt.png --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/state-of-the-state-part-ii/realtime.gif" -o static/img/copied/posts/state-of-the-state-part-ii/realtime.gif --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/state-of-the-state-part-ii/portscan.png" -o static/img/copied/posts/state-of-the-state-part-ii/portscan.png --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/state-of-the-state-part-ii/d3.png" -o static/img/copied/posts/state-of-the-state-part-ii/d3.png --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/custom-router-part-ii/bbb-network.png" -o static/img/copied/posts/custom-router-part-ii/bbb-network.png --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/custom-router-part-ii/static-route.png" -o static/img/copied/posts/custom-router-part-ii/static-route.png --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/custom-router-part-ii/demo.gif" -o static/img/copied/posts/custom-router-part-ii/demo.gif --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/notes/notes.jpg" -o static/img/copied/posts/notes/notes.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/cursive-f/f-note.jpg" -o static/img/copied/posts/cursive-f/f-note.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/cursive-f/f-post-it.jpg" -o static/img/copied/posts/cursive-f/f-post-it.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/cursive-f/long-s-google.png" -o static/img/copied/posts/cursive-f/long-s-google.png --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/overdue-invoices/cloudlinux.png" -o static/img/copied/posts/overdue-invoices/cloudlinux.png --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/rotring-rapid-pro-review/whole.jpg" -o static/img/copied/posts/rotring-rapid-pro-review/whole.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/rotring-rapid-pro-review/parts.jpg" -o static/img/copied/posts/rotring-rapid-pro-review/parts.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/rotring-rapid-pro-review/grip-detail.jpg" -o static/img/copied/posts/rotring-rapid-pro-review/grip-detail.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/rotring-rapid-pro-review/vertical.jpg" -o static/img/copied/posts/rotring-rapid-pro-review/vertical.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/retrakt-pen-review/full.jpg" -o static/img/copied/posts/retrakt-pen-review/full.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/retrakt-pen-review/clip.jpg" -o static/img/copied/posts/retrakt-pen-review/clip.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/retrakt-pen-review/detail.jpg" -o static/img/copied/posts/retrakt-pen-review/detail.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/retrakt-pen-review/parts.jpg" -o static/img/copied/posts/retrakt-pen-review/parts.jpg --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/syntax-highlighting/darkfruit.png" -o static/img/copied/posts/syntax-highlighting/darkfruit.png --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/syntax-highlighting/golang-src.png" -o static/img/copied/posts/syntax-highlighting/golang-src.png --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/syntax-highlighting/syntax.png" -o static/img/copied/posts/syntax-highlighting/syntax.png --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/arp-101/hosts.png" -o static/img/copied/posts/arp-101/hosts.png --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/arp-101/ethernet_packet_format.png" -o static/img/copied/posts/arp-101/ethernet_packet_format.png --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/arp-101/mac_table.png" -o static/img/copied/posts/arp-101/mac_table.png --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/arp-101/broadcast.png" -o static/img/copied/posts/arp-101/broadcast.png --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/break-in/cistern-log.png" -o static/img/copied/posts/break-in/cistern-log.png --create-dirs
curl "http://static.misfra.me.s3-website-us-east-1.amazonaws.com/images/posts/break-in/plots.png" -o static/img/copied/posts/break-in/plots.png --create-dirs
